# Generated by Django 5.2.6 on 2025-09-17 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=320)),
                ('recipient', models.CharField(blank=True, max_length=320)),
                ('subject', models.CharField(blank=True, max_length=1024)),
                ('body', models.TextField()),
                ('cleaned_text', models.TextField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('csv', 'CSV'), ('gmail', 'Gmail')], default='manual', max_length=20)),
                ('model_version', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
